name: Auto Unit Test and Fail Comment

on:
  push:
    branches: [ ios_develop ]
  pull_request:
    branches: [ ios_release ]
  
jobs:
  build-and-UnitTest:
    runs-on: macos-latest

    env:
      XC_VERSION: ${{ '12.1.0' }}
      XC_PROJECT: ${{ 'iOS/IssueTracker/IssueTracker.xcworkspace' }}
      XC_SCHEME: ${{ 'IssueTrackerTests' }}
      ISSUE_NUMBER: $(echo $GITHUB_REF | cut -d / -f 3)
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./iOS/IssueTracker
        run: pod install --repo-update
        shell: bash

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - name: Run Unit and UI Tests
        run: /usr/bin/xcodebuild test -workspace "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'

      # Unit Test ì„±ê³µí–ˆì„ ë•Œ Slackì— Success Message ë³´ëƒ„
      - name: Slack Success Message
        if: success()
        uses: tokorom/action-slack-incoming-webhook@v1.1.3
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ğŸ‰Unit Test SuccessğŸ‰.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Author",
                    "value": "${{ github.actor }}"
                  },
                  {
                    "title": "GitHub Pull Request URL",
                    "value": "${{ github.event.repository.html_url }}/pull/${{ env.ISSUE_NUMBER }}"
                  }
                ]
              }
            ]
      # Unit Test ì‹¤íŒ¨í–ˆì„ ë•Œ Slackì— Fail Message ë³´ëƒ„
      - name: Slack Fail Message
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@v1.1.3
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ğŸš¨Unit Test FailureğŸš¨.
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Author",
                    "value": "${{ github.actor }}"
                  },
                  {
                    "title": "GitHub Pull Request URL",
                    "value": "${{ github.event.repository.html_url }}/pull/${{  env.ISSUE_NUMBER  }}"
                  }
                ]
              }
            ]

      # Unit Test ì‹¤íŒ¨í–ˆì„ ë•Œ PRì— Fail Message ìƒì„±
      - name: Write a comment when unit test fails
        uses: actions/github-script@v3
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const ref = "${{github.ref}}"
              const pull_number = Number(ref.split("/")[2])

              await github.issues.createComment({
                issue_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Test Code FailğŸ‘‹ '
              })
